import test from 'node:test';import assert from 'node:assert/strict';
import {projects,profile} from '../src/content/portfolio.mjs';
import {escape,pathFor,homePage,projectPage,notFoundPage,concept} from '../src/templates.mjs';
import {normalizeBasePath,validateContent} from '../scripts/build.mjs';
test('nine cases with safe unique paths',()=>{assert.equal(projects.length,9);assert.doesNotThrow(()=>validateContent(projects));});
test('four featured cases',()=>assert.equal(projects.filter(p=>p.featured).length,4));
test('production and personal stack remain separate',()=>{assert.ok(projects.filter(p=>p.category.startsWith('실무')).every(p=>!p.tags.includes('React')&&!p.tags.includes('Next.js')));assert.match(projects.find(p=>p.slug==='sbom-platform').status,/진행 중/);});
test('base supports root and project path',()=>{assert.equal(normalizeBasePath('/portfolio/'),'/portfolio');assert.equal(normalizeBasePath('/'),'');assert.equal(normalizeBasePath(''),'');assert.equal(pathFor('/portfolio','projects/x/'),'/portfolio/projects/x/');});
test('base rejects invalid paths',()=>{for(const s of ['../x','/../x','/foo?bar','//evil.com','/x<script>'])assert.throws(()=>normalizeBasePath(s));});
test('HTML escaping',()=>assert.equal(escape('<a>"x" & \'y\'</a>'),'&lt;a&gt;&quot;x&quot; &amp; &#39;y&#39;&lt;/a&gt;'));
test('duplicate cases rejected',()=>assert.throws(()=>validateContent([...projects,projects[0]]),/duplicate/));
test('empty summary rejected',()=>{const p=structuredClone(projects);p[0].summary='';assert.throws(()=>validateContent(p),/summary/);});
test('unsafe media path rejected',()=>{const p=structuredClone(projects);p[0].media={src:'../../secret.jpg',alt:'x',caption:'x',width:100,height:100};assert.throws(()=>validateContent(p),/media path/);});
test('video requires a poster',()=>{const p=structuredClone(projects);p[0].media={src:'media/test.mp4',alt:'x',caption:'x',width:100,height:100,type:'video'};assert.throws(()=>validateContent(p),/poster/);});
test('unsafe link scheme rejected',()=>{const p=structuredClone(projects);p[0].links=[{label:'x',href:'javascript:alert(1)'}];assert.throws(()=>validateContent(p),/https/);});
test('content and skip link exist without JavaScript',()=>{const h=homePage('/portfolio');assert.match(h,/<main id="main" tabindex="-1">/);assert.match(h,/href="#main">본문 바로가기/);assert.ok(h.includes(profile.email));for(const p of projects)assert.ok(h.includes(`/portfolio/projects/${p.slug}/`));});
test('case pages have headings and table of contents',()=>{for(const p of projects){const h=projectPage(p,'/portfolio');assert.equal((h.match(/<h1\b/g)||[]).length,1);assert.ok(h.includes(escape(p.title)));assert.ok(h.includes('사례 목차'));}});
test('image dimensions and alternative text required',()=>{const p=structuredClone(projects[0]);p.media={src:'media/test.webp',alt:'실제 화면',width:1600,height:1250,caption:'실제 화면'};assert.match(projectPage(p,'/portfolio'),/alt="실제 화면" width="1600" height="1250" loading="lazy"/);});
test('video controls outside anchors without autoplay',()=>{const old=projects[0].media;projects[0].media={src:'media/test.mp4',poster:'media/poster.webp',alt:'동영상',caption:'실제 화면',width:1600,height:1000,type:'video'};try{const h=homePage('/portfolio');assert.match(h,/<div class="project-cover"><video/);assert.doesNotMatch(h,/<video[^>]*autoplay/);}finally{projects[0].media=old;}});
test('404 has a real home link',()=>assert.match(notFoundPage('/portfolio'),/href="\/portfolio\/#projects"/));
test('unrelated cases never reuse the build result',()=>{assert.doesNotMatch(concept(projects.find(p=>p.slug==='incremental-refactoring')),/−80/);assert.doesNotMatch(concept(projects.find(p=>p.slug==='mobile-id')),/공동/);});
