import {profile, projects} from './content/portfolio.mjs';
import {headline, featuredOrder, projectHighlights, strengths} from './content/positioning.mjs';
export const escape = value => String(value).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const pathFor = (base,path='') => `${base}/${path}`.replace(/\/+/g,'/');
const arrow='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const down='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 4v16m-6-6 6 6 6-6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const external='target="_blank" rel="noopener noreferrer"';
const chips=items=>`<ul class="tags" aria-label="사용 기술">${items.map(t=>`<li>${escape(t)}</li>`).join('')}</ul>`;
function sculpture(){return `<div class="sculpture" aria-hidden="true" data-sculpture><div class="sculpture-grid"></div><div class="sculpture-aura"></div><div class="orbit-stage"><div class="orbit-set">${Array.from({length:12},(_,i)=>{const n=Math.round(i*23/11);return `<i class="orbit" style="--n:${n};--diameter:${252+n*8}px;--angle:${n*3.6}deg;--alpha:${(.28+n*.02).toFixed(2)}"></i>`;}).join('')}<div class="orbit-core"></div></div></div><div class="sculpture-caption"><span class="tiny-dot"></span> CHANGMIN / WEB DEVELOPER</div><span class="coordinate coordinate-a">[ FRONTEND ]</span><span class="coordinate coordinate-b">[ SYSTEMS ]</span><span class="sculpture-line"></span></div>`;}
/** Concept art is explicitly labeled. No fictional product screenshot or measurement. */
export function concept(project){
 const corner=text=>`<div class="art-corner">${text}</div>`;
 switch(project.theme){
 case 'build':return `<div class="cover-art build-art" aria-hidden="true">${corner('BUILD / REIMAGINED')}<div class="build-number"><span>−80</span><i>%</i></div><div class="build-bars"><div><span>BEFORE</span><i class="bar-before"></i><b>5분대</b></div><div><span>AFTER</span><i class="bar-after"></i><b>1분대</b></div></div><div class="art-bottom">풀빌드 시간<br><strong>5분대 → 1분대</strong><span class="cover-cross">+</span></div></div>`;
 case 'water':return `<div class="cover-art water-art" aria-hidden="true">${corner('SUSINHO / WATER INTELLIGENCE')}<div class="water-rings"><i></i><i></i><i></i><i></i></div><div class="water-title">수신호<span>데이터를 이해하고,<br>다음 행동을 안내합니다.</span></div><div class="water-note"><span class="note-dot"></span><b>저수율을 보고 물관리 안내</b><span>공공데이터 → 쉬운 안내</span></div><div class="art-bottom"><span>WEB & ANDROID</span><span class="cover-cross">↗</span></div></div>`;
 case 'auth':return `<div class="cover-art auth-art" aria-hidden="true">${corner('ONE FLOW / MULTIPLE PATHS')}<div class="auth-diagram"><div class="auth-inputs"><span>공동</span><span>금융</span><span>간편</span></div><div class="auth-connectors"><i></i><i></i><i></i></div><div class="auth-core"><span>ONE</span><strong>FLOW</strong></div></div><div class="art-bottom">공동 · 금융 · 간편<br><strong>인증 처리 공통화</strong><span class="cover-cross">+</span></div></div>`;
 case 'sbom':return `<div class="cover-art sbom-art" aria-hidden="true">${corner('OSS / MADE VISIBLE')}<div class="module-stack"><div class="module-layer layer-back"><span>DEPENDENCIES</span><b>+</b></div><div class="module-layer layer-mid"><span>VULNERABILITIES</span><b>+</b></div><div class="module-layer layer-front"><span>ONE CLEAR VIEW</span><b>SBOM<span>구성요소를 연결하고,<br>의미 있는 정보로.</span></b><div class="module-dots">${'<i></i>'.repeat(12)}</div></div></div><div class="art-bottom"><span>TEAM PROJECT / IN PROGRESS</span><span class="cover-cross">↗</span></div></div>`;
 default:return `<div class="cover-art generic-art" aria-hidden="true">${corner(`ENGINEERING / ${escape(project.role.toUpperCase())}`)}<div class="generic-symbol">${project.theme==='access'?'Aa':project.theme==='refactor'?'{ }':project.theme==='identity'?'↔':'↗'}</div><div class="art-bottom">${escape(project.subtitle)}<span class="cover-cross">+</span></div></div>`;
 }
}
function projectVisual(project,base){
 const m=project.media;
 if(!m)return `${concept(project)}<span class="visual-caption">${project.theme==='build'?'실무 성과를 표현한 개념 그래픽':'프로젝트 개념 그래픽 / 실제 서비스 화면 아님'}</span>`;
 const src=escape(pathFor(base,m.src));
 if(m.type==='video')return `<video class="project-video" width="${m.width}" height="${m.height}" poster="${escape(pathFor(base,m.poster))}" controls playsinline preload="none" aria-label="${escape(m.alt)}"><source src="${src}" type="video/mp4"><a href="${src}">${escape(m.alt)} 동영상 열기</a></video><span class="visual-caption">${escape(m.caption)}</span>`;
 return `<img class="project-image" src="${src}" alt="${escape(m.alt)}" width="${m.width}" height="${m.height}" loading="lazy" decoding="async"><span class="visual-caption">${escape(m.caption)}</span>`;
}
function card(p,base,index,total){
 const url=pathFor(base,`projects/${p.slug}/`);
 const visual=p.media?.type==='video'?`<div class="project-cover">${projectVisual(p,base)}</div>`:`<a class="project-cover" href="${url}" aria-label="${escape(p.subtitle)} 상세 보기">${projectVisual(p,base)}<span class="cover-open">사례 보기 ${arrow}</span></a>`;
 // Never animate this large subtree: covers can contain 3D descendants.
 return `<article class="project-card theme-${p.theme}" id="${p.slug}">${visual}<div class="project-info" data-enter><div class="project-caption"><span>${escape(p.category)}</span><span>${String(index+1).padStart(2,'0')} / ${String(total).padStart(2,'0')}</span></div><h3><a href="${url}">${escape(p.title)}${arrow}</a></h3><p>${escape(projectHighlights[p.slug]??p.summary)}</p><div class="project-info-bottom">${chips(p.tags)}<span class="project-status">${escape(p.status)}</span></div></div></article>`;
}
function header(base,isHome){const home=pathFor(base);return `<a class="skip-link" href="#main">본문 바로가기</a><header class="site-header"><div class="nav-shell"><a class="brand" href="${home}" aria-label="성창민 포트폴리오 홈"><span class="brand-mark" aria-hidden="true">c<span>:</span>m</span><span class="brand-name">성창민</span></a><nav class="main-nav" aria-label="주요 메뉴"><a href="${isHome?'':home}#projects">프로젝트</a><a href="${isHome?'':home}#about">소개</a><a class="nav-contact" href="${isHome?'':home}#contact">연락하기 <span aria-hidden="true">↗</span></a></nav><button class="motion-toggle" type="button" aria-pressed="true" hidden data-motion-toggle><span class="motion-icon" aria-hidden="true">Ⅱ</span><span data-motion-label>모션 끄기</span></button></div></header>`;}
function footer(base){return `<footer class="site-footer"><div class="shell footer-inner"><a class="footer-wordmark" href="${pathFor(base)}">CHANGMIN<span> SEONG.</span></a><p>© 2026 성창민 <span>개발 기록</span></p><a class="back-top" href="#top">맨 위로 ${down}</a></div></footer>`;}
function contact(){return `<section class="contact-section" id="contact" aria-labelledby="contact-title"><div class="shell contact-inner"><div class="contact-overline"><span class="eyebrow">CONTACT</span><span class="contact-star" aria-hidden="true">✳</span></div><h2 id="contact-title" data-enter>함께 일할 개발자를<br><span>찾고 계신가요?</span></h2><div class="contact-bottom"><p>채용 제안이나 프로젝트에 관한 질문은<br>아래 메일로 보내주세요.</p><div class="contact-actions"><a class="contact-email" href="mailto:${profile.email}">${profile.email} ${arrow}</a><div class="contact-subactions"><button type="button" data-copy-email hidden>이메일 복사 <span aria-hidden="true">⧉</span></button><a href="${profile.github}" ${external}>GitHub <span aria-hidden="true">↗</span><span class="sr-only"> (새 창)</span></a></div></div></div><p class="copy-status sr-only" role="status" aria-live="polite" data-copy-status></p></div></section>`;}
export function layout({title,description,body,base,route='',isHome=false}){
 const canonical=`${profile.origin}${pathFor(base,route)}`;
 return `<!doctype html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow"><meta name="theme-color" content="#10121b"><!-- noindex는 검색 제외 요청이며 접근 제어가 아닙니다. --><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${escape(canonical)}"><link rel="icon" href="${pathFor(base,'assets/favicon.svg')}" type="image/svg+xml"><meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${escape(canonical)}"><meta property="og:site_name" content="성창민 포트폴리오"><meta property="og:image" content="https://indaegu.github.io/portfolio/og-image.png"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="${pathFor(base,'assets/site.css')}"><script src="${pathFor(base,'assets/site.js')}" defer></script></head><body id="top"><div class="reading-progress" aria-hidden="true"></div>${header(base,isHome)}<main id="main" tabindex="-1">${body}</main>${footer(base)}</body></html>`;
}
export function homePage(base){
 const featured=projects.filter(p=>p.featured).sort((a,b)=>featuredOrder.indexOf(a.slug)-featuredOrder.indexOf(b.slug));
 return layout({title:'성창민 | 원래 이렇게 해요를 그냥 넘기지 않는 개발자',description:profile.intro,base,isHome:true,body:`
<section class="hero" aria-labelledby="hero-title"><div class="shell hero-inner"><div class="hero-topline"><span class="eyebrow"><i class="tiny-dot"></i> FRONTEND-FOCUSED FULLSTACK DEVELOPER</span><span class="edition">SELECTED PORTFOLIO / 2026</span></div><div class="hero-content"><div class="hero-copy"><h1 id="hero-title">${headline.map((line,i)=>`<span${i===2?' class="accent-line"':''}>${escape(line)}</span>`).join('')}</h1><p class="hero-description">하나저축은행 스마트뱅킹의 화면과 서버를 개발합니다.<br>오래 걸리는 빌드와 반복되는 운영 업무를 줄여 왔습니다.</p><div class="hero-actions"><a class="button button-light" href="#projects">프로젝트 살펴보기 ${arrow}</a><a class="text-link" href="${profile.github}" ${external}>GitHub ${arrow}<span class="sr-only"> (새 창)</span></a></div></div>${sculpture()}</div><div class="hero-bottom"><div class="current"><span class="current-label">CURRENTLY</span><span>하나금융티아이 <i>/</i> 비대면 채널 개발</span></div><a class="scroll-hint" href="#projects">SCROLL TO EXPLORE ${down}</a></div></div></section>
<section class="impact-strip" aria-label="대표 경험 요약"><div class="shell impact-grid"><a href="${pathFor(base,'projects/build-performance/')}"><strong>80<span>%</span><i aria-hidden="true">↘</i></strong><span>풀빌드 시간 약 80% 단축</span></a><a href="${pathFor(base,'projects/mydata-auth/')}"><strong>3<span>→</span>1</strong><span>인증서 경로를 공통 흐름으로</span></a><a href="${pathFor(base,'projects/backoffice/')}"><strong>3<span>→</span>1</strong><span>채널별 반복 등록을 한 번으로</span></a></div></section>
<section class="work-section section" id="projects" aria-labelledby="projects-title"><div class="shell"><div class="section-heading"><div><p class="eyebrow dark-eyebrow">01 / SELECTED WORK</p><h2 id="projects-title">이런 일을 했습니다<span class="blue-dot">.</span></h2></div><p>빌드가 느렸던 이유부터<br>운영 중에 손본 기능까지.</p></div><div class="project-grid">${featured.map((p,i)=>card(p,base,i,featured.length)).join('')}</div><details class="archive" id="more-work"><summary><span><span class="eyebrow">MORE ENGINEERING STORIES</span><strong>운영 자동화·접근성·WebView 사례</strong></span><span class="archive-count">${String(projects.filter(p=>!p.featured).length).padStart(2,'0')} <i aria-hidden="true">+</i></span></summary><div class="archive-list">${projects.filter(p=>!p.featured).map(p=>`<a href="${pathFor(base,`projects/${p.slug}/`)}"><span class="archive-number">${p.index}</span><span><strong>${escape(p.subtitle)}</strong><small>${escape(projectHighlights[p.slug]??p.summary)}</small></span><span class="archive-role">${escape(p.role)}</span>${arrow}</a>`).join('')}</div></details></div></section>
<section class="about-section section" id="about" aria-labelledby="about-title"><div class="shell"><div class="section-heading about-heading"><div><p class="eyebrow">02 / ABOUT & EXPERIENCE</p><h2 id="about-title" data-enter>지금은 금융 서비스를<br><span class="muted-heading">개발하고 운영합니다.</span></h2></div><p>Vue와 Spring Boot를 쓰고,<br>개인·CoP 프로젝트에서는 React를 씁니다.</p></div><div class="about-main"><div class="about-intro"><div class="monogram" aria-hidden="true">c<span>:</span>m</div><h3>성창민 <span>Changmin Seong</span></h3><p>하나저축은행의 Vue 2·Spring Boot 기반 금융 서비스에서 인증과 WebView를 개발하고 운영합니다. 개인 프로젝트와 사내 CoP에서는 React·Next.js·TypeScript로 화면과 데이터 처리를 직접 설계하고 있습니다.</p><a class="text-link" href="mailto:${profile.email}">이메일로 이야기하기 ${arrow}</a></div><div class="career-list">${profile.experience.map((job,i)=>`<article class="career-item"><span class="career-period">${escape(job.period)}</span><h3>${escape(job.company)}${i===0?'<span class="career-current">현재</span>':''}</h3><p class="career-role">${escape(job.role)}</p><p>${escape(job.description)}</p></article>`).join('')}</div></div><div class="skills-grid">${profile.skills.map(g=>`<article class="skill-card"><p class="eyebrow">${g.caption}</p><h3>${escape(g.title)}</h3>${chips(g.items)}</article>`).join('')}</div><details class="awards"><summary><span>수상과 인정 <small>Recognition</small></span><span aria-hidden="true">+</span></summary><div>${profile.awards.map(a=>`<article><span>${a.year}</span><h3>${escape(a.title)}<small>${escape(a.description)}</small></h3></article>`).join('')}</div></details></div></section>
<section class="approach-section section" id="approach" aria-labelledby="approach-title"><div class="shell"><div class="section-heading"><div><p class="eyebrow dark-eyebrow">03 / CORE STRENGTHS</p><h2 id="approach-title" data-enter>일하면서 자주<br>맡았던 문제들<span class="blue-dot">.</span></h2></div><p>느린 빌드, 복잡한 인증,<br>반복해서 들어오는 운영 요청.</p></div><div class="principles">${strengths.map(p=>`<article data-enter><span class="principle-number">${p.number}</span><h3>${escape(p.title)}</h3><p>${escape(p.body)}</p><a href="${pathFor(base,`projects/${p.project}/`)}">${escape(p.link)} ${arrow}</a></article>`).join('')}</div></div></section>${contact()}`});}
export function projectPage(p,base){const next=projects[(projects.findIndex(x=>x.slug===p.slug)+1)%projects.length];return layout({title:`${p.subtitle} | 성창민`,description:p.summary,base,route:`projects/${p.slug}/`,body:`
<section class="case-hero"><div class="shell"><a class="back-link" href="${pathFor(base)}#${p.featured?p.slug:'more-work'}"><span aria-hidden="true">←</span> 프로젝트 목록</a><div class="case-overline"><span class="eyebrow">CASE ${p.index} / ${escape(p.category)}</span><span class="case-status">${escape(p.status)}</span></div><h1>${escape(p.title)}</h1><p class="case-lead">${escape(projectHighlights[p.slug]??p.summary)}</p><dl class="case-meta"><div><dt>PROJECT</dt><dd>${escape(p.subtitle)}</dd></div><div><dt>ROLE</dt><dd>${escape(p.role)}</dd></div><div><dt>PERIOD</dt><dd>${escape(p.period)}</dd></div></dl>${chips(p.tags)}</div></section>
<section class="case-body"><div class="shell"><figure class="case-visual theme-${p.theme}">${projectVisual(p,base)}</figure><div class="case-reading"><aside class="case-sidebar"><p class="eyebrow dark-eyebrow">IN THIS CASE</p><nav aria-label="사례 목차">${p.sections.map((s,i)=>`<a href="#section-${i+1}"><span>0${i+1}</span>${escape(s.heading)}</a>`).join('')}</nav><div class="case-result"><strong>${escape(p.metric.value)}</strong><span>${escape(p.metric.label)}</span></div></aside><div class="case-article">${p.sections.map((s,i)=>`<section id="section-${i+1}" aria-labelledby="heading-${i+1}"><span class="case-section-number">0${i+1} /</span><h2 id="heading-${i+1}">${escape(s.heading)}</h2>${s.body.map(t=>`<p>${escape(t)}</p>`).join('')}</section>`).join('')}<blockquote><p>${escape(p.takeaway)}</p><cite>작업을 돌아보며</cite></blockquote>${p.links?`<div class="case-links">${p.links.map(l=>`<a class="button button-dark" href="${escape(l.href)}" ${external}>${escape(l.label)} ${arrow}<span class="sr-only"> (새 창)</span></a>`).join('')}</div>`:''}</div></div><a class="next-case" href="${pathFor(base,`projects/${next.slug}/`)}"><span class="eyebrow dark-eyebrow">NEXT STORY / ${next.index}</span><strong>${escape(next.subtitle)}</strong>${arrow}</a></div></section>${contact()}`});}
export function notFoundPage(base){return layout({title:'페이지를 찾을 수 없습니다 | 성창민',description:'성창민 포트폴리오의 홈으로 돌아갑니다.',base,route:'404.html',body:`<section class="not-found shell"><p class="eyebrow">404 / NOT FOUND</p><h1>이 경로의 이야기는<br>찾을 수 없습니다.</h1><p>주소를 확인하거나 프로젝트 목록에서 다시 찾아주세요.</p><a class="button button-light" href="${pathFor(base)}#projects">프로젝트로 돌아가기 ${arrow}</a></section>`});}
